<?php
/**
 * Models from schema: AldosEngine version 0.1
 * Code generated by TransformTask
 *
 */

/**
 * @todo: Copy this file to app/lang/<lang>/users.php
 * Modify the values accordingly
 */
return array(
    '_name' => 'User',
    '_name_plural' => 'Users',
    'sid' => 'Sid',
    'created_dt' => 'Created Dt',
    'updated_dt' => 'Updated Dt',
    'updated_counter' => 'Updated Counter',
    'uuid' => 'Uuid',
    'org_name' => 'Organization',
    'org_sid' => 'Org Sid',
    'id' => 'Id',
    'password' => 'Password',
    'name' => 'Name',
    'first_name' => 'First Name',
    'middle_name' => 'Middle Name',
    'last_name' => 'Last Name',
    'lc_name' => 'Lc Name',
    'display_name' => 'Display Name',
    'dob' => 'Dob',
    'phone' => 'Phone',
    'email' => 'Email',
    'permalink' => 'Permalink',
    'activation_code' => 'Activation Code',
    'security_question' => 'Security Question',
    'security_answer' => 'Security Answer',
    'session_timestamp' => 'Session Timestamp',
    'last_session_ip' => 'Last Session Ip',
    'last_session_dt' => 'Last Session Dt',
    'login_fail_counter' => 'Login Fail Counter',
    'active' => 'Active',
    'status' => 'Status',
    'default_lang_cd' => 'Default Lang Cd',
    'timezone' => 'Timezone',
    'expiry_dt' => 'Expiry Dt',
    'type' => 'Type',
    'params_text' => 'Params Text',
);
