<?php
/**
 * Models from schema: AldosEngine version 0.1
 * Code generated by TransformTask
 *
 */


/**
 * Controller class that provides REST API to User resource
 */
class AccountController extends \GenericServiceController {

	public function __construct() {
		parent::__construct('layouts.workspace', 'svc:account', 'Account');
	}

	public function createAuxData($record) {
		$auxdata = array();

		$auxdata['opt_PaymentPeriod'] = array('monthly', 'bi-monthly');

		return $auxdata;
	}

	public function showAuxData($record) {
		$auxdata = array();

		return $auxdata;
	}

	public function editAuxData($record) {

		return $this->createAuxData($record);
	}

	public function indexOfFormat($format, $records) {

		$csv_output = '';
	    foreach ($records as $row) {
	        $csv_output .= implode(',', $row->toArray()) . "\n";
	    }
	    $csv_output = rtrim($csv_output, "\n");
	    //$output =  mb_convert_encoding($csv_output, 'UCS-2LE', 'UTF-8');
	    $output =  $csv_output;

	    $headers = array(
	        'Content-Type' => 'text/csv',
	        'charset' => 'utf-8',
	        'Content-Disposition' => 'attachment; filename="account.csv"',
	    );
	 
	    return Response::make($output, 200, $headers);
	}

}