<?php
/**
 * Models from schema: AldosEngine version 0.1
 * Code generated by TransformTask
 *
 */


/**
 * Controller class that provides REST API to User resource
 */
class AccountApiController extends \GenericServiceApiController {

	public function __construct() {
		parent::__construct('svc:account', 'Account');
	}

}