<?php
/**
 * Models from schema: AldosEngine version 0.1
 * Code generated by TransformTask
 *
 */


/**
 * Controller class that provides REST API to User resource
 */
class IssueController extends \GenericServiceController {

	public function __construct() {
		parent::__construct('layouts.workspace', 'svc:issue', 'Issue');
	}

	public function editAuxData($record) {
		$auxdata = array();

		return $auxdata;
	}


}