<?php
/**
 * Models from schema: AldosEngine version 0.1
 * Code generated by TransformTask
 *
 */


/**
 * Controller class that provides REST API to User resource
 */
class TransactionController extends \GenericServiceController {

	public function __construct() {
		parent::__construct('layouts.workspace', 'svc:transaction', 'Transaction');
	}

	public function editAuxData($record) {
		$auxdata = array();

		return $auxdata;
	}

	private function getRoleService()
	{
		return App::make('df_role_service');
	}

}