<?php
/**
 * Models from schema: market version 0.1
 * Code generated by TransformTask
 *
 */

class Account extends Eloquent {

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'accounts';

    /**
     * The primary key column name.
     *
     * @var string
     */
    protected $primaryKey = 'ID';

    /**
     * To disable created_at and updated_at.
     *
     * @var boolean
     */
    public $timestamps = false;


    /**
     * The field list for mass assignment.
     *
     * @var array
     */
    protected $fillable = array('ID', 'Name' ,'PledgeAmount'
      ,'PledgeDate', 'PaymentPeriod' ,'LastPaymentDate', 'PaidAmount'
      ,'RemainingAmount', 'RemindLetterSent', 'RemindLetterSentDate');

    /**
     * Validation rules for creation
     *
     * @var array
     */
    private static $validation_rules_create = array(
        'Name' => 'required|min:2',
        'PledgeAmount' => 'min:1'
        );

    /**
     * Validation rules for update
     *
     * @var array
     */
    private static $validation_rules_update = array(
        'Name' => 'required|min:2',
        'PledgeAmount' => 'min:1'
        );

    /**
     * Returns the validation object
     */
    public static function validator($fields, $is_create = true)
    {
        $rules = ($is_create) ? static::$validation_rules_create : static::$validation_rules_update;
        $validator = Validator::make($fields, $rules);

        return $validator;
    }

    public function transactions()
    {
        return $this->hasMany('Transaction');
    }

    public function getName()
    {
        return $this->Name;
    }
}
